# Generated by Django 5.2.3 on 2026-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corral', models.CharField(max_length=40)),
                ('remitente', models.CharField(max_length=140)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('marca_imagen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
