# Generated by Django 5.2.3 on 2026-06-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Remate = apps.get_model("registros", "Remate")
    PreferenciaRemateUsuario = apps.get_model("registros", "PreferenciaRemateUsuario")
    Registro = apps.get_model("registros", "Registro")
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])

    remate_inicial, _ = Remate.objects.get_or_create(
        nombre="Remate inicial",
        defaults={"finalizado": False},
    )

    Registro.objects.filter(remate__isnull=True).update(remate=remate_inicial)

    for usuario in User.objects.all():
        PreferenciaRemateUsuario.objects.update_or_create(usuario_id=usuario.id, defaults={"remate": remate_inicial})


def backwards(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('finalizado', models.BooleanField(default=False)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaRemateUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_remate', to=settings.AUTH_USER_MODEL)),
                ('remate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencias_usuario', to='registros.remate')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='remate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='registros.remate'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
