# Generated by Django 5.2.3 on 2026-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remate_preferenciaremateusuario_registro_remate'),
    ]

    operations = [
        migrations.AddField(
            model_name='remate',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remate',
            name='lugar',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
