# Generated by Django 5.2.15 on 2026-06-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_seed_mapa_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='registro',
            name='corral',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='remitente',
            field=models.CharField(db_index=True, max_length=140),
        ),
    ]
