# Generated by Django 5.2.15 on 2026-08-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_add_indices_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='rp',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='remate',
            name='habilitar_rp',
            field=models.BooleanField(default=False),
        ),
    ]
