# Generated by Django 5.2.15 on 2026-08-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_registro_rp_remate_habilitar_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rp',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
