"""Layout estatico de corrales derivado de PLANO RURAL.xlsx (Hoja1)."""

MAP_ROWS = 35
MAP_COLS = 47

CORRALES_DISPONIBLES = [
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "90",
    "91",
    "92",
    "93",
    "94",
    "95",
    "96",
    "97",
    "98",
    "99",
    "100",
    "101",
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "108",
    "109",
    "110",
    "111",
    "112",
    "113",
    "114",
    "115",
    "116",
    "117",
    "118",
    "119",
    "120",
    "121",
    "122",
    "123",
    "124",
    "125",
    "126",
    "127",
    "128",
    "129",
    "130",
]

CORRALES_LAYOUT = [
    {"row": 1, "col": 17, "label": "PISTA", "kind": "pista", "row_span": 3, "col_span": 8},
    {"row": 2, "col": 1, "label": "PASILLO", "kind": "pasillo", "row_span": 2, "col_span": 16},
    {"row": 2, "col": 25, "label": "PASILLO", "kind": "pasillo", "row_span": 2, "col_span": 11},
    {"row": 2, "col": 38, "label": "PASILLO", "kind": "pasillo", "row_span": 2, "col_span": 7},
    {"row": 4, "col": 1, "label": "TORIL", "kind": "toril", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 4, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 2},
    {"row": 4, "col": 6, "label": "10", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 9, "label": "19", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 12, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 2},
    {"row": 4, "col": 14, "label": "28", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 17, "label": "37", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 20, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 2},
    {"row": 4, "col": 22, "label": "46", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 25, "label": "55", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 28, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 2},
    {"row": 4, "col": 30, "label": "64", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 33, "label": "73", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 36, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 2},
    {"row": 4, "col": 38, "label": "82", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 41, "label": "91", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 4, "col": 44, "label": "PASILLO", "kind": "pasillo", "row_span": 18, "col_span": 1},
    {"row": 6, "col": 1, "label": "2", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 6, "label": "11", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 9, "label": "20", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 14, "label": "29", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 17, "label": "38", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 22, "label": "47", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 25, "label": "56", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 30, "label": "65", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 33, "label": "74", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 38, "label": "83", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 6, "col": 41, "label": "92", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 1, "label": "3", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 6, "label": "12", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 9, "label": "21", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 14, "label": "30", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 17, "label": "39", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 22, "label": "48", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 25, "label": "57", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 30, "label": "66", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 33, "label": "75", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 38, "label": "84", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 8, "col": 41, "label": "93", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 1, "label": "4", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 6, "label": "13", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 9, "label": "22", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 14, "label": "31", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 17, "label": "40", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 22, "label": "49", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 25, "label": "58", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 30, "label": "67", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 33, "label": "76", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 38, "label": "85", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 10, "col": 41, "label": "94", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 1, "label": "5", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 6, "label": "14", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 9, "label": "23", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 14, "label": "32", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 17, "label": "41", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 22, "label": "50", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 25, "label": "59", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 30, "label": "68", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 33, "label": "77", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 38, "label": "86", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 12, "col": 41, "label": "95", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 1, "label": "6", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 6, "label": "15", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 9, "label": "24", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 14, "label": "33", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 17, "label": "42", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 22, "label": "51", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 25, "label": "60", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 30, "label": "69", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 33, "label": "78", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 38, "label": "87", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 14, "col": 41, "label": "96", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 1, "label": "7", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 6, "label": "16", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 9, "label": "25", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 14, "label": "34", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 17, "label": "43", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 22, "label": "52", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 25, "label": "61", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 30, "label": "70", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 33, "label": "79", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 38, "label": "88", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 16, "col": 41, "label": "97", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 1, "label": "8", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 6, "label": "17", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 9, "label": "26", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 14, "label": "35", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 17, "label": "44", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 22, "label": "53", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 25, "label": "62", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 30, "label": "71", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 33, "label": "80", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 38, "label": "89", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 18, "col": 41, "label": "98", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 1, "label": "9", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 6, "label": "18", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 9, "label": "27", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 14, "label": "36", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 17, "label": "45", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 22, "label": "54", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 25, "label": "63", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 30, "label": "72", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 33, "label": "81", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 38, "label": "90", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 20, "col": 41, "label": "99", "kind": "corral", "row_span": 2, "col_span": 3},
    {"row": 22, "col": 1, "label": "PASILLO", "kind": "pasillo", "row_span": 2, "col_span": 44},
    {"row": 24, "col": 1, "label": "119", "kind": "corral", "row_span": 4, "col_span": 3},
    {"row": 24, "col": 4, "label": "PASILLO", "kind": "pasillo", "row_span": 8, "col_span": 2},
    {"row": 24, "col": 6, "label": "106", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 8, "label": "105", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 10, "label": "104", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 12, "label": "103", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 14, "label": "102", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 16, "label": "101", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 18, "label": "100", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 24, "col": 20, "label": "PASILLO", "kind": "pasillo", "row_span": 6, "col_span": 2},
    {"row": 24, "col": 22, "label": "112", "kind": "corral", "row_span": 6, "col_span": 4},
    {"row": 24, "col": 26, "label": "111", "kind": "corral", "row_span": 6, "col_span": 4},
    {"row": 24, "col": 30, "label": "110", "kind": "corral", "row_span": 6, "col_span": 4},
    {"row": 24, "col": 34, "label": "109", "kind": "corral", "row_span": 6, "col_span": 3},
    {"row": 24, "col": 37, "label": "108", "kind": "corral", "row_span": 6, "col_span": 3},
    {"row": 24, "col": 40, "label": "107", "kind": "corral", "row_span": 6, "col_span": 4},
    {"row": 24, "col": 44, "label": "PASILLO", "kind": "pasillo", "row_span": 8, "col_span": 1},
    {"row": 27, "col": 6, "label": "118", "kind": "corral", "row_span": 3, "col_span": 3},
    {"row": 27, "col": 9, "label": "117", "kind": "corral", "row_span": 3, "col_span": 3},
    {"row": 27, "col": 12, "label": "116", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 27, "col": 14, "label": "115", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 27, "col": 16, "label": "114", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 27, "col": 18, "label": "113", "kind": "corral", "row_span": 3, "col_span": 2},
    {"row": 28, "col": 1, "label": "120", "kind": "corral", "row_span": 4, "col_span": 3},
    {"row": 30, "col": 6, "label": "PASILLO", "kind": "pasillo", "row_span": 2, "col_span": 38},
    {"row": 32, "col": 1, "label": "130", "kind": "corral", "row_span": 4, "col_span": 3},
    {"row": 32, "col": 4, "label": "129", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 9, "label": "128", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 14, "label": "127", "kind": "corral", "row_span": 4, "col_span": 4},
    {"row": 32, "col": 18, "label": "126", "kind": "corral", "row_span": 4, "col_span": 4},
    {"row": 32, "col": 22, "label": "125", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 27, "label": "124", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 32, "label": "123", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 37, "label": "122", "kind": "corral", "row_span": 4, "col_span": 5},
    {"row": 32, "col": 42, "label": "121", "kind": "corral", "row_span": 4, "col_span": 3},
]
